### PR TITLE
Devicetree

### PR DESCRIPTION
**Pull request by jameyhicks**
This pull request contains support for device tree for risc-v.

It was split from the DMA pull request and a kernel config option was added to specify an address for the devicetree until a better mechanism is defined.

### CODE REVIEW

**Comment by sashimi-yzh** [comment]
I want to add a Xilinx ethernet adapter as a device of the rocketchip system. I apply this patch to the `priv-1.9` branch. But I find that after unpacking initramfs, the unflattened tree structure is overwritten, which leads to invalid memory accessing.
```
[   10.550000] [hart #0][drivers/of/platform.c,451,of_platform_populate] of_node_get(root) = fffffffffd11bce0
[   10.560000] [hart #0][drivers/of/platform.c,456,of_platform_populate] root = fffffffffd11bce0, root->name = 0101370300813683, root->type = f8050ce301813783, root->full_name = 00045c63fff4041b
[   10.580000] [hart #0][drivers/of/platform.c,459,of_platform_populate] root>parent = fff90913ffe48593, root->child = f51ff06f00058493, root->sibling = 00064503fff60613
```
All outputs above are addresses. Except for the address of root, all other fields in the root device_node are unexpected.

**Comment by jameyhicks** [comment]
This sounds like a problem in unpacking the initramfs. You might also try commenting out the call to ioremap(dt) in arch/riscv/kernel/devicetree.c.

**Comment by sashimi-yzh** [comment]
Hi Jamey!

I try to comment out `ioremap(dt)`, but it does not help. I think somewhere of the initramfs code gets the same pages as the `of_root` pointing to. I try to let `init/initramfs.c: populate_rootfs()` return immediately, instead of doing unpacking, then `arch/riscv/kernel/devicetree.c: devicetree_populate()` works well.

I notice that you mentioned Xilinx AXI ethernet subsystem in #30. Have you ever made the ethernet work? And which version of kernel did you use?

**Comment by jameyhicks** [comment]
I was using a 4.1 branch. I haven't touched this for about 6 months so my memory of it is fuzzy.

It was before the 1.9 system spec.

While testing system integration, I used qemu-riscv with the memory-mapped peripherals implemented by a Xilinx FPGA.

I did get as far as acquiring an address with DHCP using the Xilinx AXI Ethernet Subsystem. We had some problems with the ethernet not being able to receive packets soon after DHCP completed. I handed off the work to someone else before we resolved that problem.

**Comment by sashimi-yzh** [comment]
I will take a look at the 4.1 branch. Thank you for sharing your experience! It may help me a lot!

**Comment by jameyhicks** [comment]
There are some other commits of interest, if you use the Xilinx AXI Interrupt controller for example, on this branch: https://github.com/jameyhicks/riscv-linux/commits/linux-4.1.y-bluespec

**Comment by sashimi-yzh** [comment]
Wow, thanks again!

**Comment by terpstra** [comment]
Just an update, we will be including device tree support hopefully within the next month. We will want to locate the FDT from an SBI call, however.

**Comment by sashimi-yzh** [comment]
Great! :)

**Comment by jameyhicks** [comment]
That is excellent news! An SBI call to locate the FDT makes perfect sense.

**Comment by sorear** [comment]
I think the current plan is to pass a pointer in a0.

**Pull request closed without merging**
