### PR TITLE
include,asm,pgtable.h: add PAGE_KERNEL_EXEC definition

### PR DESCRIPTION
**Pull request by sashimi-yzh**
* In mm/vmalloc.c, `PAGE_KERNEL` will be used as `PAGE_KERNEL_EXEC` if
  `PAGE_KERNEL_EXEC` is not defined. But `PAGE_KERNEL` defined in
  arch/riscv/include/asm/pgtable.h does not set the X bit. This makes
  `vmalloc_exec()` get non-executable memory in RISC-V, which is unexpected.

### CODE REVIEW

**Comment by aswaterman** [comment]
@palmer-dabbelt can you review & apply to priv-1.10 branch instead of master?

**Comment by palmer-dabbelt** [comment]
This looks good to me.  I'll merge it manually.

Thanks!

**Comment by sashimi-yzh** [comment]
I have changed the base branch to priv-1.10 :)

**Comment by palmer-dabbelt** [comment]
This is 4bc06d383a707be601885ab3e4bea760818e0f29.

**Pull request closed without merging**
