### PR TITLE
For discussion - previous typo requests are also included - don't know what that is about.

### PR DESCRIPTION
**Pull request by DSHorner**
reduce accesses to stale memory and csr in exception handling

(I haven't even assembled yet - but hoped this might be helpful at submission v2 review)

in entry.S most of the code is executed with interrupts disabled.:
No read or write to TASK_TI_*_SP when entry from kernel mode.
Consolidated scr access:
    no csrr to recover kernel tp
    user register csr read and kernel mode flag consolidated
    earlier sstatus restore to avoid interrupt disable csrs

This patch also positions for removal of TASK_TI_*_SP save areas.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
Can you point me to the commits you actually want merged?  I think this is just a rebase problem, but I can merge things manually.

**Comment by DSHorner** [comment]
this pull request certainly has patch I didn't intend.
Sorry for the noise.

**Comment by DSHorner** [comment]
the patch is:
 	reduce accesses to stale memory and csr in exception handling 

Thanks for your time.

**Comment by DSHorner** [comment]
This is the end objective of this series - to remove the TASK_TI_*_SP save areas.

https://github.com/DSHorner/riscv-linux/commit/fea40877890e1e045d1079900710beb1b17f9ffb

**Comment by DSHorner** [comment]
PT_KERN_TP will alias to PT_SCAUSE in asm-offsets.c for the patch that removes TASK_TI_*_SP.

**Comment by palmer-dabbelt** [comment]
IIRC we swapped this around because upstream didn't want TP to be on the stack, as that makes it easier to turn stack bugs into security problems.

**Pull request closed without merging**
