### PR TITLE
Add -mstrict-align to CFLAGS

### PR DESCRIPTION
**Pull request by palmer-dabbelt**

### CODE REVIEW

**Comment by sorear** [comment]
Is this specific to Linux, or is there a broader problem with `-mno-strict-align`?

**Comment by palmer-dabbelt** [comment]
It's just a reminder to test a theory about a tricky bug we're trying to
track down.

**Comment by terpstra** [comment]
newest toolchain causes radeon driver in 4.11 to oops

**Comment by palmer-dabbelt** [comment]
This ended up landing

**Pull request closed without merging**
