### PR TITLE
Enabled HAVE_PERF_EVENTS for RISC-V

### PR DESCRIPTION
**Pull request by solomatnikov**
Still WIP

### CODE REVIEW

**Comment by solomatnikov** [comment]
@palmer-dabbelt this can be merged as is to enable at least SW perf infrastructure.

HW perf counters will take some time

**Comment by NonerKao** [comment]
We are currently working on the perf port as well, and our goal in this stage is to make cycle, instret, and time register visible as HW events.  Maybe we can have some discussion on the implementation decisions?

Thanks.

**Comment by solomatnikov** [comment]
Sure, let's discuss.

My plan is to add SBI calls to use configurable HW perf counters.

**Comment by palmer-dabbelt** [comment]
Thanks.  I've pulled this into riscv-all.

**Comment by NonerKao** [comment]
@solomatnikov 
Sure, for the write access to performance counters in machine mode,  we will need a SBI for this.

Also, I am interested in the **implementation paradigm** for `riscv/kernel/perf_event.c`, by which I mean the ways other architectures have implemented `perf`.  Some of them utilize `platform driver` framework (arm, arm64) , some connect to the `pmc` unit (powerpc, s390, tile), and some just call `perf_pmu_register` with `"cpu"` and `TYPE_RAW` (mips).

All those method works, but they treat distinct PMUs in different ways.  I suppose we need to come up with a consensus on which paradigm we are going to apply, because in the foreseeable future, there will be at least three PMUs:
- Base system, simulators like `spike` and `qemu`: only `instret`, `cycle` and `time` counters are supported.
- Sifive family: Hifive Unleashed dev-board, and others in the future.
- Andes family: AndesCore N25 and NX25, and others in the future.

As I mentioned previously, our goal is to make `cycle`, `instret`, and `time` register visible as HW events when using `perf` program, which is a general part for all RISC-V platforms.  We estimate this goal to be done in two weeks, and currently we are trying the `pmc` paradigm.  But considering that you may have done far more than us, it is good for the whole RISC-V community to exchange some implementation ideas at this early stage of the `perf` port.

Thanks and sorry for the late reply, since we were enjoying our traditional lunar new year holiday during the past week.  I hope this discussion can minimize our duplication of work in implementing `perf`.

**Pull request closed without merging**
